### ISSUE TITLE
Emoji Problems

### ISSUE THREAD

**Issue by Lucreativedesign** [milselarch/RCV-tele-bot#28]
Hi there! Thx for the latests updates!

Small detail, I used some emojis in the poll options to create labels of sort. But I'm seeing errors after the first person registers. ????? for example

I used these emoji's: 🔥 🤷🏻‍♂️ 🌙 ⛺️ 🏖️ 

This one worked though! ☀️ 

Thank you!

**Comment by milselarch** [comment]
heyo thanks for bringing it up  
its probably a string encoding / decoding issue, i'll go look into it

**Comment by milselarch** [comment]
heyo the emojis turning to ??? should be fixed now - turns out the database connection + tables wasn't using UTF-8 so emojis weren't being saved properly in the DB  
(also I nuked the database cause database migrations for another change i was making weren't working, so apologies if theres any inconvenience caused)
